// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKYHkw_k9mUXcTjXF093t3_eYdT2zIWTE',
    appId: '1:709517146208:web:38bf9b2ac688311f22ab05',
    messagingSenderId: '709517146208',
    projectId: 'hypechat-app',
    authDomain: 'hypechat-app.firebaseapp.com',
    storageBucket: 'hypechat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhphGvUH29Q0sV6njOPNTD3qCjyQClJUk',
    appId: '1:709517146208:android:9564dad53e0cd06f22ab05',
    messagingSenderId: '709517146208',
    projectId: 'hypechat-app',
    storageBucket: 'hypechat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR0219wb__mTFr-LuNIro3E8GtEJDGj90',
    appId: '1:709517146208:ios:f60df08fdb0009cf22ab05',
    messagingSenderId: '709517146208',
    projectId: 'hypechat-app',
    storageBucket: 'hypechat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR0219wb__mTFr-LuNIro3E8GtEJDGj90',
    appId: '1:709517146208:ios:f60df08fdb0009cf22ab05',
    messagingSenderId: '709517146208',
    projectId: 'hypechat-app',
    storageBucket: 'hypechat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKYHkw_k9mUXcTjXF093t3_eYdT2zIWTE',
    appId: '1:709517146208:web:f1c09dc118abda4322ab05',
    messagingSenderId: '709517146208',
    projectId: 'hypechat-app',
    authDomain: 'hypechat-app.firebaseapp.com',
    storageBucket: 'hypechat-app.firebasestorage.app',
  );
}
